# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    download_directory: '../public/download'
    admin_email: 'huy@gmail.com'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $globalParam: 'this is global param used by all service defined in this file'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\AppController:
        bind:
            $logger : '@monolog.logger.doctrine'
    App\Service\Gift:
        arguments:
            $paramService: 'this is param service'
            $adminEmail: '%admin_email%'
#            $secondService : '@App\Service\SecondService'
        properties:
            my : '@App\Service\SecondService'
            logger : '@monolog.logger'

    app.second_service:
        alias: App\Service\SecondService

        public: true


    App\Service\SecondService:
        arguments:
            $first: 'first thing'
#    App\Listener\CacheClear:
#        tags: [kernel.cache_clearer]
#        tags: { name: kernel.event_listener, event: kernel.response}]

#    App\Listener\VideoCreatedListener:
#        tags:
#            - { name: kernel.event_listener, event: video.created.event}

    App\Service\Interface\UploadInterface: '@App\Service\LocalUploadService'
